-- Seed Users
INSERT INTO users (name, email, password, role)
VALUES ('Ammar User', 'user@example.com', '$2a$10$iG5ZOKLkhVUfdumJRaxTYeq/Z7baNGXKO71ABRy0OAvULjuknZPIW', 'USER');

INSERT INTO users (name, email, password, role)
VALUES ('Ammar Admin', 'admin@example.com', '$2a$10$ADWL0R.d9lnKyUsuVDUGl.HtYE.cl7kKk6fy57v7KSJ9mHxWtzgOm', 'ADMIN');

-- Seed Products
INSERT INTO products (name, description, price)
VALUES
  ('Nasi Goreng Kampung Reguler', 'Nasi goreng bumbu kampung dengan telur varian reguler', 18000.00),
  ('Mie Ayam Jamur Reguler', 'Mie ayam dengan topping jamur dan pangsit varian reguler', 17000.00),
  ('Sate Ayam Madura Reguler', 'Sate ayam bumbu kacang khas Madura varian reguler', 25000.00),
  ('Bakso Urat Reguler', 'Bakso urat kuah kaldu sapi varian reguler', 22000.00),
  ('Soto Ayam Lamongan Reguler', 'Soto ayam kuning dengan koya varian reguler', 20000.00),
  ('Ayam Geprek Sambal Bawang Reguler', 'Ayam crispy geprek sambal bawang varian reguler', 23000.00),
  ('Rendang Daging Reguler', 'Rendang sapi berbumbu rempah varian reguler', 32000.00),
  ('Gado-Gado Jakarta Reguler', 'Sayur rebus dengan bumbu kacang varian reguler', 19000.00),
  ('Ketoprak Reguler', 'Ketupat tahu bihun bumbu kacang varian reguler', 17000.00),
  ('Pecel Lele Reguler', 'Lele goreng dengan sambal dan lalapan varian reguler', 21000.00),
  ('Rawon Surabaya Reguler', 'Rawon daging kuah kluwek varian reguler', 28000.00),
  ('Nasi Uduk Komplit Reguler', 'Nasi uduk dengan telur dan ayam suwir varian reguler', 22000.00),
  ('Nasi Kuning Reguler', 'Nasi kuning dengan lauk pilihan varian reguler', 20000.00),
  ('Mie Goreng Jawa Reguler', 'Mie goreng manis gurih khas Jawa varian reguler', 19000.00),
  ('Kwetiau Goreng Sapi Reguler', 'Kwetiau goreng dengan irisan sapi varian reguler', 27000.00),
  ('Capcay Kuah Reguler', 'Sayuran segar kuah gurih varian reguler', 18000.00),
  ('Ikan Bakar Jimbaran Reguler', 'Ikan bakar bumbu kecap pedas varian reguler', 35000.00),
  ('Udang Saus Padang Reguler', 'Udang tumis saus Padang varian reguler', 33000.00),
  ('Cumi Goreng Tepung Reguler', 'Cumi goreng renyah saus tartar varian reguler', 30000.00),
  ('Tahu Telur Surabaya Reguler', 'Tahu telur dengan bumbu kacang petis varian reguler', 21000.00),
  ('Tempe Mendoan Reguler', 'Tempe goreng tepung setengah kering varian reguler', 12000.00),
  ('Pempek Kapal Selam Reguler', 'Pempek isi telur dengan cuko varian reguler', 24000.00),
  ('Siomay Bandung Reguler', 'Siomay ikan dengan bumbu kacang varian reguler', 20000.00),
  ('Batagor Bandung Reguler', 'Bakso tahu goreng saus kacang varian reguler', 21000.00),
  ('Martabak Telur Mini Reguler', 'Martabak telur gurih porsi mini varian reguler', 18000.00),
  ('Bubur Ayam Reguler', 'Bubur ayam dengan cakwe dan kerupuk varian reguler', 16000.00),
  ('Lontong Sayur Reguler', 'Lontong sayur labu dengan telur varian reguler', 18000.00),
  ('Nasi Liwet Reguler', 'Nasi gurih dengan ayam dan sambal varian reguler', 24000.00),
  ('Ayam Bakar Taliwang Reguler', 'Ayam bakar pedas khas Lombok varian reguler', 29000.00),
  ('Bebek Goreng Reguler', 'Bebek goreng renyah sambal hijau varian reguler', 33000.00),
  ('Es Teh Manis Reguler', 'Teh manis dingin varian reguler', 6000.00),
  ('Es Jeruk Reguler', 'Jeruk peras dingin varian reguler', 8000.00),
  ('Jus Alpukat Reguler', 'Jus alpukat dengan cokelat varian reguler', 15000.00),
  ('Jus Mangga Reguler', 'Jus mangga segar varian reguler', 14000.00),
  ('Kopi Susu Gula Aren Reguler', 'Kopi susu dengan gula aren varian reguler', 18000.00),
  ('Teh Tarik Reguler', 'Teh susu tarik hangat atau dingin varian reguler', 12000.00),
  ('Es Cendol Reguler', 'Cendol santan gula merah varian reguler', 13000.00),
  ('Es Campur Reguler', 'Es campur buah dan sirup varian reguler', 16000.00),
  ('Air Mineral Reguler', 'Air mineral botol varian reguler', 5000.00),
  ('Lemon Tea Reguler', 'Teh lemon segar varian reguler', 10000.00),
  ('Nasi Goreng Kampung Spesial', 'Nasi goreng bumbu kampung dengan telur varian spesial', 20000.00),
  ('Mie Ayam Jamur Spesial', 'Mie ayam dengan topping jamur dan pangsit varian spesial', 19000.00),
  ('Sate Ayam Madura Spesial', 'Sate ayam bumbu kacang khas Madura varian spesial', 27000.00),
  ('Bakso Urat Spesial', 'Bakso urat kuah kaldu sapi varian spesial', 24000.00),
  ('Soto Ayam Lamongan Spesial', 'Soto ayam kuning dengan koya varian spesial', 22000.00),
  ('Ayam Geprek Sambal Bawang Spesial', 'Ayam crispy geprek sambal bawang varian spesial', 25000.00),
  ('Rendang Daging Spesial', 'Rendang sapi berbumbu rempah varian spesial', 34000.00),
  ('Gado-Gado Jakarta Spesial', 'Sayur rebus dengan bumbu kacang varian spesial', 21000.00),
  ('Ketoprak Spesial', 'Ketupat tahu bihun bumbu kacang varian spesial', 19000.00),
  ('Pecel Lele Spesial', 'Lele goreng dengan sambal dan lalapan varian spesial', 23000.00),
  ('Rawon Surabaya Spesial', 'Rawon daging kuah kluwek varian spesial', 30000.00),
  ('Nasi Uduk Komplit Spesial', 'Nasi uduk dengan telur dan ayam suwir varian spesial', 24000.00),
  ('Nasi Kuning Spesial', 'Nasi kuning dengan lauk pilihan varian spesial', 22000.00),
  ('Mie Goreng Jawa Spesial', 'Mie goreng manis gurih khas Jawa varian spesial', 21000.00),
  ('Kwetiau Goreng Sapi Spesial', 'Kwetiau goreng dengan irisan sapi varian spesial', 29000.00),
  ('Capcay Kuah Spesial', 'Sayuran segar kuah gurih varian spesial', 20000.00),
  ('Ikan Bakar Jimbaran Spesial', 'Ikan bakar bumbu kecap pedas varian spesial', 37000.00),
  ('Udang Saus Padang Spesial', 'Udang tumis saus Padang varian spesial', 35000.00),
  ('Cumi Goreng Tepung Spesial', 'Cumi goreng renyah saus tartar varian spesial', 32000.00),
  ('Tahu Telur Surabaya Spesial', 'Tahu telur dengan bumbu kacang petis varian spesial', 23000.00),
  ('Tempe Mendoan Spesial', 'Tempe goreng tepung setengah kering varian spesial', 14000.00),
  ('Pempek Kapal Selam Spesial', 'Pempek isi telur dengan cuko varian spesial', 26000.00),
  ('Siomay Bandung Spesial', 'Siomay ikan dengan bumbu kacang varian spesial', 22000.00),
  ('Batagor Bandung Spesial', 'Bakso tahu goreng saus kacang varian spesial', 23000.00),
  ('Martabak Telur Mini Spesial', 'Martabak telur gurih porsi mini varian spesial', 20000.00),
  ('Bubur Ayam Spesial', 'Bubur ayam dengan cakwe dan kerupuk varian spesial', 18000.00),
  ('Lontong Sayur Spesial', 'Lontong sayur labu dengan telur varian spesial', 20000.00),
  ('Nasi Liwet Spesial', 'Nasi gurih dengan ayam dan sambal varian spesial', 26000.00),
  ('Ayam Bakar Taliwang Spesial', 'Ayam bakar pedas khas Lombok varian spesial', 31000.00),
  ('Bebek Goreng Spesial', 'Bebek goreng renyah sambal hijau varian spesial', 35000.00),
  ('Es Teh Manis Spesial', 'Teh manis dingin varian spesial', 8000.00),
  ('Es Jeruk Spesial', 'Jeruk peras dingin varian spesial', 10000.00),
  ('Jus Alpukat Spesial', 'Jus alpukat dengan cokelat varian spesial', 17000.00),
  ('Jus Mangga Spesial', 'Jus mangga segar varian spesial', 16000.00),
  ('Kopi Susu Gula Aren Spesial', 'Kopi susu dengan gula aren varian spesial', 20000.00),
  ('Teh Tarik Spesial', 'Teh susu tarik hangat atau dingin varian spesial', 14000.00),
  ('Es Cendol Spesial', 'Cendol santan gula merah varian spesial', 15000.00),
  ('Es Campur Spesial', 'Es campur buah dan sirup varian spesial', 18000.00),
  ('Air Mineral Spesial', 'Air mineral botol varian spesial', 7000.00),
  ('Lemon Tea Spesial', 'Teh lemon segar varian spesial', 12000.00),
  ('Nasi Goreng Kampung Komplit', 'Nasi goreng bumbu kampung dengan telur varian komplit', 22000.00),
  ('Mie Ayam Jamur Komplit', 'Mie ayam dengan topping jamur dan pangsit varian komplit', 21000.00),
  ('Sate Ayam Madura Komplit', 'Sate ayam bumbu kacang khas Madura varian komplit', 29000.00),
  ('Bakso Urat Komplit', 'Bakso urat kuah kaldu sapi varian komplit', 26000.00),
  ('Soto Ayam Lamongan Komplit', 'Soto ayam kuning dengan koya varian komplit', 24000.00),
  ('Ayam Geprek Sambal Bawang Komplit', 'Ayam crispy geprek sambal bawang varian komplit', 27000.00),
  ('Rendang Daging Komplit', 'Rendang sapi berbumbu rempah varian komplit', 36000.00),
  ('Gado-Gado Jakarta Komplit', 'Sayur rebus dengan bumbu kacang varian komplit', 23000.00),
  ('Ketoprak Komplit', 'Ketupat tahu bihun bumbu kacang varian komplit', 21000.00),
  ('Pecel Lele Komplit', 'Lele goreng dengan sambal dan lalapan varian komplit', 25000.00),
  ('Rawon Surabaya Komplit', 'Rawon daging kuah kluwek varian komplit', 32000.00),
  ('Nasi Uduk Komplit Komplit', 'Nasi uduk dengan telur dan ayam suwir varian komplit', 26000.00),
  ('Nasi Kuning Komplit', 'Nasi kuning dengan lauk pilihan varian komplit', 24000.00),
  ('Mie Goreng Jawa Komplit', 'Mie goreng manis gurih khas Jawa varian komplit', 23000.00),
  ('Kwetiau Goreng Sapi Komplit', 'Kwetiau goreng dengan irisan sapi varian komplit', 31000.00),
  ('Capcay Kuah Komplit', 'Sayuran segar kuah gurih varian komplit', 22000.00),
  ('Ikan Bakar Jimbaran Komplit', 'Ikan bakar bumbu kecap pedas varian komplit', 39000.00),
  ('Udang Saus Padang Komplit', 'Udang tumis saus Padang varian komplit', 37000.00),
  ('Cumi Goreng Tepung Komplit', 'Cumi goreng renyah saus tartar varian komplit', 34000.00),
  ('Tahu Telur Surabaya Komplit', 'Tahu telur dengan bumbu kacang petis varian komplit', 25000.00),
  ('Tempe Mendoan Komplit', 'Tempe goreng tepung setengah kering varian komplit', 16000.00),
  ('Pempek Kapal Selam Komplit', 'Pempek isi telur dengan cuko varian komplit', 28000.00),
  ('Siomay Bandung Komplit', 'Siomay ikan dengan bumbu kacang varian komplit', 24000.00),
  ('Batagor Bandung Komplit', 'Bakso tahu goreng saus kacang varian komplit', 25000.00),
  ('Martabak Telur Mini Komplit', 'Martabak telur gurih porsi mini varian komplit', 22000.00),
  ('Bubur Ayam Komplit', 'Bubur ayam dengan cakwe dan kerupuk varian komplit', 20000.00),
  ('Lontong Sayur Komplit', 'Lontong sayur labu dengan telur varian komplit', 22000.00),
  ('Nasi Liwet Komplit', 'Nasi gurih dengan ayam dan sambal varian komplit', 28000.00),
  ('Ayam Bakar Taliwang Komplit', 'Ayam bakar pedas khas Lombok varian komplit', 33000.00),
  ('Bebek Goreng Komplit', 'Bebek goreng renyah sambal hijau varian komplit', 37000.00),
  ('Es Teh Manis Komplit', 'Teh manis dingin varian komplit', 10000.00),
  ('Es Jeruk Komplit', 'Jeruk peras dingin varian komplit', 12000.00),
  ('Jus Alpukat Komplit', 'Jus alpukat dengan cokelat varian komplit', 19000.00),
  ('Jus Mangga Komplit', 'Jus mangga segar varian komplit', 18000.00),
  ('Kopi Susu Gula Aren Komplit', 'Kopi susu dengan gula aren varian komplit', 22000.00),
  ('Teh Tarik Komplit', 'Teh susu tarik hangat atau dingin varian komplit', 16000.00),
  ('Es Cendol Komplit', 'Cendol santan gula merah varian komplit', 17000.00),
  ('Es Campur Komplit', 'Es campur buah dan sirup varian komplit', 20000.00),
  ('Air Mineral Komplit', 'Air mineral botol varian komplit', 9000.00),
  ('Lemon Tea Komplit', 'Teh lemon segar varian komplit', 14000.00),
  ('Nasi Goreng Kampung Pedas', 'Nasi goreng bumbu kampung dengan telur varian pedas', 24000.00),
  ('Mie Ayam Jamur Pedas', 'Mie ayam dengan topping jamur dan pangsit varian pedas', 23000.00),
  ('Sate Ayam Madura Pedas', 'Sate ayam bumbu kacang khas Madura varian pedas', 31000.00),
  ('Bakso Urat Pedas', 'Bakso urat kuah kaldu sapi varian pedas', 28000.00),
  ('Soto Ayam Lamongan Pedas', 'Soto ayam kuning dengan koya varian pedas', 26000.00),
  ('Ayam Geprek Sambal Bawang Pedas', 'Ayam crispy geprek sambal bawang varian pedas', 29000.00),
  ('Rendang Daging Pedas', 'Rendang sapi berbumbu rempah varian pedas', 38000.00),
  ('Gado-Gado Jakarta Pedas', 'Sayur rebus dengan bumbu kacang varian pedas', 25000.00),
  ('Ketoprak Pedas', 'Ketupat tahu bihun bumbu kacang varian pedas', 23000.00),
  ('Pecel Lele Pedas', 'Lele goreng dengan sambal dan lalapan varian pedas', 27000.00),
  ('Rawon Surabaya Pedas', 'Rawon daging kuah kluwek varian pedas', 34000.00),
  ('Nasi Uduk Komplit Pedas', 'Nasi uduk dengan telur dan ayam suwir varian pedas', 28000.00),
  ('Nasi Kuning Pedas', 'Nasi kuning dengan lauk pilihan varian pedas', 26000.00),
  ('Mie Goreng Jawa Pedas', 'Mie goreng manis gurih khas Jawa varian pedas', 25000.00),
  ('Kwetiau Goreng Sapi Pedas', 'Kwetiau goreng dengan irisan sapi varian pedas', 33000.00),
  ('Capcay Kuah Pedas', 'Sayuran segar kuah gurih varian pedas', 24000.00),
  ('Ikan Bakar Jimbaran Pedas', 'Ikan bakar bumbu kecap pedas varian pedas', 41000.00),
  ('Udang Saus Padang Pedas', 'Udang tumis saus Padang varian pedas', 39000.00),
  ('Cumi Goreng Tepung Pedas', 'Cumi goreng renyah saus tartar varian pedas', 36000.00),
  ('Tahu Telur Surabaya Pedas', 'Tahu telur dengan bumbu kacang petis varian pedas', 27000.00),
  ('Tempe Mendoan Pedas', 'Tempe goreng tepung setengah kering varian pedas', 18000.00),
  ('Pempek Kapal Selam Pedas', 'Pempek isi telur dengan cuko varian pedas', 30000.00),
  ('Siomay Bandung Pedas', 'Siomay ikan dengan bumbu kacang varian pedas', 26000.00),
  ('Batagor Bandung Pedas', 'Bakso tahu goreng saus kacang varian pedas', 27000.00),
  ('Martabak Telur Mini Pedas', 'Martabak telur gurih porsi mini varian pedas', 24000.00),
  ('Bubur Ayam Pedas', 'Bubur ayam dengan cakwe dan kerupuk varian pedas', 22000.00),
  ('Lontong Sayur Pedas', 'Lontong sayur labu dengan telur varian pedas', 24000.00),
  ('Nasi Liwet Pedas', 'Nasi gurih dengan ayam dan sambal varian pedas', 30000.00),
  ('Ayam Bakar Taliwang Pedas', 'Ayam bakar pedas khas Lombok varian pedas', 35000.00),
  ('Bebek Goreng Pedas', 'Bebek goreng renyah sambal hijau varian pedas', 39000.00),
  ('Es Teh Manis Pedas', 'Teh manis dingin varian pedas', 12000.00),
  ('Es Jeruk Pedas', 'Jeruk peras dingin varian pedas', 14000.00),
  ('Jus Alpukat Pedas', 'Jus alpukat dengan cokelat varian pedas', 21000.00),
  ('Jus Mangga Pedas', 'Jus mangga segar varian pedas', 20000.00),
  ('Kopi Susu Gula Aren Pedas', 'Kopi susu dengan gula aren varian pedas', 24000.00),
  ('Teh Tarik Pedas', 'Teh susu tarik hangat atau dingin varian pedas', 18000.00),
  ('Es Cendol Pedas', 'Cendol santan gula merah varian pedas', 19000.00),
  ('Es Campur Pedas', 'Es campur buah dan sirup varian pedas', 22000.00),
  ('Air Mineral Pedas', 'Air mineral botol varian pedas', 11000.00),
  ('Lemon Tea Pedas', 'Teh lemon segar varian pedas', 16000.00),
  ('Nasi Goreng Kampung Keju', 'Nasi goreng bumbu kampung dengan telur varian keju', 26000.00),
  ('Mie Ayam Jamur Keju', 'Mie ayam dengan topping jamur dan pangsit varian keju', 25000.00),
  ('Sate Ayam Madura Keju', 'Sate ayam bumbu kacang khas Madura varian keju', 33000.00),
  ('Bakso Urat Keju', 'Bakso urat kuah kaldu sapi varian keju', 30000.00),
  ('Soto Ayam Lamongan Keju', 'Soto ayam kuning dengan koya varian keju', 28000.00),
  ('Ayam Geprek Sambal Bawang Keju', 'Ayam crispy geprek sambal bawang varian keju', 31000.00),
  ('Rendang Daging Keju', 'Rendang sapi berbumbu rempah varian keju', 40000.00),
  ('Gado-Gado Jakarta Keju', 'Sayur rebus dengan bumbu kacang varian keju', 27000.00),
  ('Ketoprak Keju', 'Ketupat tahu bihun bumbu kacang varian keju', 25000.00),
  ('Pecel Lele Keju', 'Lele goreng dengan sambal dan lalapan varian keju', 29000.00),
  ('Rawon Surabaya Keju', 'Rawon daging kuah kluwek varian keju', 36000.00),
  ('Nasi Uduk Komplit Keju', 'Nasi uduk dengan telur dan ayam suwir varian keju', 30000.00),
  ('Nasi Kuning Keju', 'Nasi kuning dengan lauk pilihan varian keju', 28000.00),
  ('Mie Goreng Jawa Keju', 'Mie goreng manis gurih khas Jawa varian keju', 27000.00),
  ('Kwetiau Goreng Sapi Keju', 'Kwetiau goreng dengan irisan sapi varian keju', 35000.00),
  ('Capcay Kuah Keju', 'Sayuran segar kuah gurih varian keju', 26000.00),
  ('Ikan Bakar Jimbaran Keju', 'Ikan bakar bumbu kecap pedas varian keju', 43000.00),
  ('Udang Saus Padang Keju', 'Udang tumis saus Padang varian keju', 41000.00),
  ('Cumi Goreng Tepung Keju', 'Cumi goreng renyah saus tartar varian keju', 38000.00),
  ('Tahu Telur Surabaya Keju', 'Tahu telur dengan bumbu kacang petis varian keju', 29000.00),
  ('Tempe Mendoan Keju', 'Tempe goreng tepung setengah kering varian keju', 20000.00),
  ('Pempek Kapal Selam Keju', 'Pempek isi telur dengan cuko varian keju', 32000.00),
  ('Siomay Bandung Keju', 'Siomay ikan dengan bumbu kacang varian keju', 28000.00),
  ('Batagor Bandung Keju', 'Bakso tahu goreng saus kacang varian keju', 29000.00),
  ('Martabak Telur Mini Keju', 'Martabak telur gurih porsi mini varian keju', 26000.00),
  ('Bubur Ayam Keju', 'Bubur ayam dengan cakwe dan kerupuk varian keju', 24000.00),
  ('Lontong Sayur Keju', 'Lontong sayur labu dengan telur varian keju', 26000.00),
  ('Nasi Liwet Keju', 'Nasi gurih dengan ayam dan sambal varian keju', 32000.00),
  ('Ayam Bakar Taliwang Keju', 'Ayam bakar pedas khas Lombok varian keju', 37000.00),
  ('Bebek Goreng Keju', 'Bebek goreng renyah sambal hijau varian keju', 41000.00),
  ('Es Teh Manis Keju', 'Teh manis dingin varian keju', 14000.00),
  ('Es Jeruk Keju', 'Jeruk peras dingin varian keju', 16000.00),
  ('Jus Alpukat Keju', 'Jus alpukat dengan cokelat varian keju', 23000.00),
  ('Jus Mangga Keju', 'Jus mangga segar varian keju', 22000.00),
  ('Kopi Susu Gula Aren Keju', 'Kopi susu dengan gula aren varian keju', 26000.00),
  ('Teh Tarik Keju', 'Teh susu tarik hangat atau dingin varian keju', 20000.00),
  ('Es Cendol Keju', 'Cendol santan gula merah varian keju', 21000.00),
  ('Es Campur Keju', 'Es campur buah dan sirup varian keju', 24000.00),
  ('Air Mineral Keju', 'Air mineral botol varian keju', 13000.00),
  ('Lemon Tea Keju', 'Teh lemon segar varian keju', 18000.00);
